#!/bin/sh
set -eu

exec java \
  -Dloader.main=cn.inkforge.core.platform.db.SchemaGuardCommand \
  -cp /app/inkforge-core-api.jar \
  org.springframework.boot.loader.launch.PropertiesLauncher \
  "$@"
