"""长篇独立分集影视化 CLI 命令集合。"""

from .episode_production import VIDEO_EPISODE_PRODUCTION_COMMAND_SPECS
from .episodes import VIDEO_EPISODE_COMMAND_SPECS
from .projects import VIDEO_PROJECT_COMMAND_SPECS
from .visuals import VIDEO_VISUAL_COMMAND_SPECS

VIDEO_COMMAND_SPECS = (
    *VIDEO_PROJECT_COMMAND_SPECS,
    *VIDEO_EPISODE_COMMAND_SPECS,
    *VIDEO_VISUAL_COMMAND_SPECS,
    *VIDEO_EPISODE_PRODUCTION_COMMAND_SPECS,
)

__all__ = ["VIDEO_COMMAND_SPECS"]
