"""长篇章节影视化 CLI 命令集合。"""

from .adaptations import VIDEO_ADAPTATION_COMMAND_SPECS
from .post_production import VIDEO_POST_PRODUCTION_COMMAND_SPECS
from .projects import VIDEO_PROJECT_COMMAND_SPECS
from .renders import VIDEO_RENDER_COMMAND_SPECS
from .visuals import VIDEO_VISUAL_COMMAND_SPECS

VIDEO_COMMAND_SPECS = (
    *VIDEO_PROJECT_COMMAND_SPECS,
    *VIDEO_ADAPTATION_COMMAND_SPECS,
    *VIDEO_VISUAL_COMMAND_SPECS,
    *VIDEO_RENDER_COMMAND_SPECS,
    *VIDEO_POST_PRODUCTION_COMMAND_SPECS,
)

__all__ = ["VIDEO_COMMAND_SPECS"]
