import type { CreativeOperationKind } from "@/shared/contracts/creative-operation";
import type { CoreAgentId, WritingState } from "@/agents/graph/state";

export type ToolProfileState = Partial<Pick<WritingState, "currentOperation" | "activeArtifactId" | "artifactReview" | "pendingAgentCall">>;

const HIDDEN_AGENT_TOOL_NAMES = new Set([
  "get_character_list",
  "propose_update_character",
  "propose_update_character_status",
  "propose_update_outline",
  "propose_add_foreshadowing",
  "propose_resolve_foreshadowing",
]);

const REVIEW_TOOLS = [
  "get_active_review_artifact",
  "get_review_artifact",
  "submit_evaluation",
];

const SHOW_ARTIFACT = ["show_review_artifact"];

const OPERATION_TOOL_PROFILES: Record<CreativeOperationKind, string[]> = {
  answer_question: [
    "get_novel_info",
    "list_available_data",
    "search_lore",
    "list_outline_summary",
    "get_outline_node",
    "list_characters_summary",
    "get_character_detail",
    "get_style_profile",
  ],
  create_lore: [
    "get_novel_info",
    "list_available_data",
    "list_characters_summary",
    "get_character_detail",
    "list_factions_summary",
    "get_faction_detail",
    "list_locations_summary",
    "get_location_detail",
    "list_items_summary",
    "get_item_detail",
    "list_glossaries_summary",
    "get_glossary_detail",
    "search_lore",
    "find_similar_lore",
    "propose_updates",
    "start_update_builder",
    "append_update_batch",
    "put_update_text_block",
    "put_update_item_text_block",
    "put_update_item_text_blocks",
    "finish_update_builder",
    ...SHOW_ARTIFACT,
  ],
  revise_lore: [
    "get_novel_info",
    "list_available_data",
    "list_characters_summary",
    "get_character_detail",
    "list_factions_summary",
    "get_faction_detail",
    "list_locations_summary",
    "get_location_detail",
    "list_items_summary",
    "get_item_detail",
    "list_glossaries_summary",
    "get_glossary_detail",
    "search_lore",
    "find_similar_lore",
    "propose_updates",
    "start_update_builder",
    "append_update_batch",
    "put_update_text_block",
    "put_update_item_text_block",
    "put_update_item_text_blocks",
    "finish_update_builder",
    ...SHOW_ARTIFACT,
  ],
  create_outline: [
    "get_novel_info",
    "list_available_data",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "get_plot_progress",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "propose_updates",
    "start_update_builder",
    "append_update_batch",
    "append_outline_tree",
    "put_update_text_block",
    "put_update_item_text_block",
    "put_update_item_text_blocks",
    "finish_update_builder",
    ...SHOW_ARTIFACT,
  ],
  revise_outline: [
    "get_novel_info",
    "list_available_data",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "get_plot_progress",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "get_recent_chapters",
    "propose_updates",
    "start_update_builder",
    "append_update_batch",
    "append_outline_tree",
    "put_update_text_block",
    "put_update_item_text_block",
    "put_update_item_text_blocks",
    "finish_update_builder",
    ...SHOW_ARTIFACT,
  ],
  plan_chapter: [
    "get_novel_info",
    "list_available_data",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "get_plot_progress",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "get_recent_chapters",
    "submit_beat_plan",
    ...SHOW_ARTIFACT,
  ],
  write_chapter: [
    "get_novel_info",
    "get_style_profile",
    "get_recent_chapters",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "search_lore",
    "get_faction_detail",
    "get_location_detail",
    "get_item_detail",
    "get_glossary_detail",
    "begin_artifact_output",
    ...SHOW_ARTIFACT,
  ],
  rewrite_scene: [
    "get_novel_info",
    "get_style_profile",
    "get_recent_chapters",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "search_lore",
    "get_faction_detail",
    "get_location_detail",
    "get_item_detail",
    "get_glossary_detail",
    "begin_artifact_output",
    ...SHOW_ARTIFACT,
  ],
  review_chapter: [
    "get_novel_info",
    "get_style_profile",
    "get_recent_chapters",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "submit_quality_report",
    "submit_validation_report",
    ...REVIEW_TOOLS,
  ],
  sync_lore: [
    "get_novel_info",
    "get_recent_chapters",
    "list_characters_summary",
    "get_character_detail",
    "search_lore",
    "get_faction_detail",
    "get_location_detail",
    "get_item_detail",
    "get_glossary_detail",
    "propose_updates",
    "start_update_builder",
    "append_update_batch",
    "put_update_text_block",
    "put_update_item_text_block",
    "put_update_item_text_blocks",
    "finish_update_builder",
    ...SHOW_ARTIFACT,
  ],
  manage_foreshadowing: [
    "get_novel_info",
    "list_characters_summary",
    "get_character_detail",
    "list_outline_summary",
    "get_outline_node",
    "get_plot_progress",
    "list_foreshadowings_summary",
    "get_foreshadowing_detail",
    "get_recent_chapters",
    "propose_updates",
    ...SHOW_ARTIFACT,
  ],
};

export function filterToolNamesForOperation(
  agentId: CoreAgentId,
  toolNames: string[],
  state?: ToolProfileState
): string[] {
  const visible = toolNames.filter((name) => !HIDDEN_AGENT_TOOL_NAMES.has(name));
  const kind = state?.currentOperation?.kind;
  if (!kind) return visible;

  const allowed = new Set(OPERATION_TOOL_PROFILES[kind]);
  if (state.activeArtifactId || state.artifactReview?.activeArtifactId || state.pendingAgentCall?.toAgent === agentId) {
    allowed.add("get_review_artifact");
    allowed.add("get_active_review_artifact");
    if (agentId === "编辑" || agentId === "校验") allowed.add("submit_evaluation");
  }

  return visible.filter((name) => allowed.has(name));
}
