from .author import SYSTEM_PROMPT as AUTHOR_SYSTEM_PROMPT
from .editor import SYSTEM_PROMPT as EDITOR_SYSTEM_PROMPT
from .lore import SYSTEM_PROMPT as LORE_SYSTEM_PROMPT
from .plot import SYSTEM_PROMPT as PLOT_SYSTEM_PROMPT
from .validator import SYSTEM_PROMPT as VALIDATOR_SYSTEM_PROMPT

__all__ = [
    "AUTHOR_SYSTEM_PROMPT",
    "EDITOR_SYSTEM_PROMPT",
    "LORE_SYSTEM_PROMPT",
    "PLOT_SYSTEM_PROMPT",
    "VALIDATOR_SYSTEM_PROMPT",
]
